#!/bin/bash

set -e

export OVN_LOGDIR=${SNAP_COMMON}/log/ovn
export OVN_RUNDIR=${SNAP_COMMON}/run/ovn
export OVN_SYSCONFDIR=${SNAP_COMMON}/etc
export OVN_PKGDATADIR=${SNAP}/usr/share/ovn
export OVN_BINDIR=${SNAP}/usr/bin
export OVN_SBINDIR=${SNAP}/usr/sbin
export OVS_RUNDIR=${SNAP_COMMON}/run/openvswitch

if [ `basename $1` = 'ovn-ctl' ]
then
    mkdir -p ${OVN_LOGDIR}
    mkdir -p ${OVN_RUNDIR}
    mkdir -p ${OVN_SYSCONFDIR}/ovn
fi

exec $@
