name: openstack-hypervisor
version: xena
base: core20
summary: OpenStack Hypervisor
description: |
  The OpenStack Hypervisor snap provides the requires components
  to operate a cloud hypervisor as part of an OpenStack deployment.
grade: devel
confinement: strict
environment:
  LC_ALL: C
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH
  # Standard library components must have priority in module name resolution: https://storyboard.openstack.org/#!/story/2007806
  PYTHONPATH: $PYTHONPATH:$SNAP/usr/lib/python3.8:$SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.8/site-packages
  # /usr/lib/$SNAPCRAFT_ARCH_TRIPLET not added to LD_LIBRARY_PATH by default
  # Causes:
  # CVE-2020-27348: A potentially empty LD_LIBRARY_PATH has been set for environment in '.'.
  # The current working directory will be added to the library path if empty.
  # This can cause unexpected libraries to be loaded.
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  # OVN runtime configuration
  OVN_LOGDIR: $SNAP_COMMON/log/ovn
  OVN_RUNDIR: $SNAP_COMMON/run/ovn
  OVN_SYSCONFDIR: $SNAP_COMMON/etc
  OVN_PKGDATADIR: $SNAP/usr/share/ovn
  OVN_BINDIR: $SNAP/usr/bin
  OVN_SBINDIR: $SNAP/usr/sbin
  # OVS runtime configuration
  OVS_LOGDIR: $SNAP_COMMON/log/openvswitch
  OVS_RUNDIR: $SNAP_COMMON/run/openvswitch
  OVS_SYSCONFDIR: $SNAP_COMMON/etc
  OVS_PKGDATADIR: $SNAP/usr/share/openvswitch
  OVS_BINDIR: $SNAP/usr/bin
  OVS_SBINDIR: $SNAP/usr/sbin

architectures:
  - build-on: amd64
  - build-on: arm64

system-usernames:
  snap_daemon: shared

layout:
  /usr/local/bin:
    symlink: $SNAP/usr/local/bin
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/ceph:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/ceph
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  /usr/lib/libvirt:
    symlink: $SNAP/usr/lib/libvirt
  /usr/share/libvirt:
    symlink: $SNAP/usr/share/libvirt
  /usr/share/qemu:
    symlink: $SNAP/usr/share/qemu
  # For UEFI Support, bindmount the OVMF and AAVMF directories
  # appropriately. UEFI support is required for aarch64.
  /usr/share/OVMF:
    symlink: $SNAP/usr/share/OVMF
  /usr/share/AAVMF:
    symlink: $SNAP/usr/share/AAVMF

apps:
  # Libvirt
  libvirtd:
    command: usr/sbin/libvirtd --pid $SNAP_DATA/libvirt.pid --listen
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - netlink-connector
      - netlink-audit
      - libvirt
      - opengl
      - raw-usb
      - hardware-observe
      - hugepages-control
      - kvm
      - kernel-module-observe
      - process-control
      - mount-observe
      - block-devices
      - microstack-support
    # Make sure KillMode=process is set in the resulting systemd unit instead of
    # the default KillMode=control-group to avoid the situation where stopping
    # libvirtd causes the forced power off scenario for all VMs; it also affects
    # snap refreshes as libvirtd is restarted in this case.
    # Removing the snap will still result in VMs being forcefully powered off which
    # is intended.
    stop-mode: sigterm

  virtlogd:
    command: usr/sbin/virtlogd --pid $SNAP_DATA/virtlogd.pid
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - microstack-support
  virsh:
    command: usr/bin/virsh
    plugs:
      - network
      - microstack-support

  # Openvswitch
  ovs-vswitchd:
    command: usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server --no-monitor start
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovsdb-server stop
    after: [ovsdb-server]
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - openvswitch-support
      - process-control
      - system-trace
      - hardware-observe
      - hugepages-control
      - microstack-support
  ovsdb-server:
    command: "bin/ovsdb-server-service"
    stop-command: usr/share/openvswitch/scripts/ovs-ctl --no-ovs-vswitchd stop
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support

  # OVN
  ovn-controller:
    command: usr/share/ovn/scripts/ovn-ctl start_controller --no-monitor
    stop-command: usr/share/ovn/scripts/ovn-ctl stop_controller --no-monitor --restart
    daemon: forking
    plugs:
      - network
      - network-bind
      - network-control
      - openvswitch-support
      - process-control
      - system-trace
      - microstack-support
    after:
      - ovsdb-server
      - ovs-vswitchd

  # OVS/OVN cli tools
  ovn-appctl:
    command: usr/bin/ovn-appctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-trace:
    command: usr/bin/ovn-trace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-detrace:
    command: usr/bin/ovn-detrace
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-nbctl:
    command: usr/bin/ovn-nbctl
    plugs:
      - network
      - network-bind
      - microstack-support
  ovn-sbctl:
    command: usr/bin/ovn-sbctl
    plugs:
      - network
      - network-bind
      - process-control
      - microstack-support

  ovs-vsctl:
    command: usr/bin/ovs-vsctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-appctl:
    command: usr/bin/ovs-appctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-ofctl:
    command: usr/bin/ovs-ofctl
    plugs:
      - network
      - process-control
      - microstack-support
  ovs-dpctl:
    command: usr/bin/ovs-dpctl
    plugs:
      - network
      - process-control
      - microstack-support

  nova-compute:
    command: 'bin/nova-compute-service'
    after: [libvirtd]
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - firewall-control
      - hardware-observe
      - kvm
      - microstack-support
      # Needs access to block devices so that blockdev --flushbufs works.
      - block-devices

  neutron-ovn-metadata-agent:
    command: 'bin/neutron-ovn-metadata-agent-service'
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe
      - microstack-support

  nova-api-metadata:
    command: 'bin/nova-api-metadata-service'
    daemon: simple
    plugs:
      - network
      - network-bind
      - firewall-control
      - microstack-support

  hypervisor-config-service:
    command: 'bin/gunicorn openstack_hypervisor.api:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind unix:$SNAP_COMMON/run/hypervisor-config/unix.socket'
    restart-condition: on-failure
    daemon: simple
    slots:
      - hypervisor-config
    plugs:
      - network
      - network-bind
      - microstack-support
    install-mode: enable
    sockets:
      unix:
        listen-stream: $SNAP_COMMON/run/hypervisor-config/unix.socket
        socket-mode: 0666

parts:
  # Add Ubuntu Cloud Archive sources.
  # Allows us to fetch things such as updated libvirt.
  uca-sources:
    plugin: nil
    build-packages:
      - ubuntu-cloud-keyring
      - software-properties-common
      - dpkg-dev  # We'll need to manipulate sources later.
    override-pull: |
      add-apt-repository -s cloud-archive:xena
      apt-key update
      apt update
      snapcraftctl pull

  qemu:
    source: https://git.launchpad.net/ubuntu/+source/qemu
    source-type: git
    source-branch: ubuntu/focal-updates
    source-depth: 1
    plugin: autotools
    after:
      - uca-sources
    build-environment:
      # Workaround for https://bugs.launchpad.net/snapcraft/+bug/1860766
      - LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/ceph:$SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH
    stage-packages:
      - seabios
      - ipxe-qemu
      - freeglut3 # provides libglut.so.3
      - libnuma1
      - libspice-server1
      - libasound2
      - libasyncns0
      - libbluetooth3
      - libboost-iostreams1.71.0
      - libboost-random1.71.0
      - libboost-system1.71.0
      - libboost-thread1.71.0
      - libcaca0
      - libfdt1
      - libflac8
      - libglib2.0-0
      - libglu1-mesa
      - libiscsi7
      - libjpeg-turbo8
      - libnspr4
      - libnss3
      - libogg0
      - libopus0
      - libpixman-1-0
      - libpulse0
      - librados2
      - librbd1
      - libsdl1.2debian
      - libslang2
      - libsndfile1
      - libusb-1.0-0
      - libusbredirparser1
      - libvorbis0a
      - libvorbisenc2
      - libx11-6
      - libxi6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libpng16-16
      - libaio1
      - libasn1-8-heimdal
      - libbrotli1
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libssh-4
      - libwind0-heimdal
      # UEFI Support, required on arm64
      - on arm64:
        - qemu-efi-aarch64
        - qemu-efi-arm
      - on amd64:
        - ovmf
    build-packages:
      - acpica-tools
      - libaio-dev
      - libasound2-dev
      - libattr1-dev
      - libbluetooth-dev
      - libcap-dev
      - libcap-ng-dev
      - libcurl4-gnutls-dev
      - libfdt-dev
      - libiscsi-dev
      - libncurses5-dev
      - try: [libnuma-dev]
      - libpixman-1-dev
      - libpulse-dev
      - librados-dev
      - librbd-dev
      - libsasl2-dev
      - libsdl1.2-dev
      - try: [libspice-server-dev, libspice-protocol-dev]
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - linux-libc-dev
      - uuid-dev
      - xfslibs-dev
      - libjpeg-dev
      - zlib1g-dev
      - libpng-dev
      - wget
      - dpkg-dev
      - gcc
    autotools-configure-parameters:
      - --disable-blobs
      - --prefix=/usr
      - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
      - --firmwarepath=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/seabios:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/qemu:/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/ipxe/qemu
      - --disable-user
      - --disable-linux-user
      - --disable-bsd-user
      - --disable-vhost-user
      - --enable-system
      - --target-list=x86_64-softmmu,aarch64-softmmu
      - --disable-xen
    override-build: |
      dpkg-source --before-build .
      snapcraftctl build

  kvm-support:
    plugin: nil
    stage-packages:
    - try: [msr-tools]

  libvirt:
    source: https://git.launchpad.net/ubuntu/+source/libvirt
    source-type: git
    source-branch: ubuntu/focal-updates
    source-subdir: build-subdir
    source-depth: 1
    after:
      - qemu
      - uca-sources
    plugin: autotools
    build-packages:
    - libxml2-dev
    - libxml-libxml-perl
    - libcurl4-gnutls-dev
    - libncurses5-dev
    - libreadline-dev
    - zlib1g-dev
    - libgcrypt20-dev
    - libgnutls28-dev
    - libyajl-dev
    - libpcap0.8-dev
    - libaudit-dev
    - libdevmapper-dev
    - libpciaccess-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - libxml2-utils
    - uuid-dev
    - try: [libnuma-dev]
    - python-all
    - python-six
    - wget
    - dpkg-dev
    - xsltproc
    - libapparmor-dev
    - rsync
    - open-iscsi
    - python3-docutils
    - gettext
    stage-packages:
    - dmidecode
    - dnsmasq
    - iptables
    - genisoimage
    - libxml2
    - libyajl2
    - try: [libnuma1]
    - libcurl3-gnutls
    - libpcap0.8
    - libpciaccess0
    # libvirt uses the pm-is-supported tool.
    - pm-utils
    - ebtables
    - apparmor
    - libapparmor1
    autotools-configure-parameters:
    - --with-qemu
    - --without-bhyve
    - --without-xen
    - --without-openvz
    - --without-vmware
    - --without-xenapi
    - --without-esx
    - --without-hyperv
    - --without-lxc
    - --without-vz
    - --without-vbox
    - --without-uml
    - --without-sasl
    - --without-storage-sheepdog
    - --without-storage-rbd
    - --without-storage-lvm
    - --without-selinux
    - --without-docs
    - --with-chrdev-lock-files=/run/lock
    - --with-storage-iscsi
    # TODO(dmitriis): re-enable once a workaround is found for subprocess' RPATH handling.
    # - --with-apparmor
    - --without-apparmor
    # NOTE: the install prefix will be different from the actual location on snap installation.
    - --prefix=/usr
    - --bindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/bin
    - --sbindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin
    - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/libexec
    - --libdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib
    - --includedir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/include
    - --oldincludedir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/include
    - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common/etc/
    - DNSMASQ=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dnsmasq
    - DMIDECODE=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dmidecode
    - OVSVSCTL=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/local/bin/ovs-vsctl
    - IPTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/iptables-legacy
    - IP6TABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/ip6tables-legacy
    - EBTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/ebtables-legacy
    build-environment:
      # Libraries under /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/x86_64-linux-gnu are not added to the
      # runpath by default. This is OK for parent processes which get LD_LIBRARY_PATH set properly but not
      # for the child processes they spawn since the environment variables are not passed down to children by default after execve(2).
      # `readelf -d /snap/microstack/current/usr/libexec/virt-aa-helper` should return something like:
      # (RUNPATH)            Library runpath: [/snap/microstack/current/usr/lib:/snap/microstack/current/usr/lib/x86_64-linux-gnu:...]
      - LDFLAGS: '$LDFLAGS -Wl,-rpath=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib -Wl,-rpath=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET -Wl,-rpath=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib -Wl,-rpath=/lib/$SNAPCRAFT_ARCH_TRIPLET -Wl,-rpath=/lib/'
    override-build: |
      dpkg-source --before-build .
      logger `echo -n $PWD`
      # Prevent libvirt from attempting to run setgroups
      echo "

      #undef HAVE_SETGROUPS
      #undef HAVE_SETEUID
      " >> config-post.h

      # See https://bugs.launchpad.net/snapcraft/+bug/1882255
      mkdir build-subdir
      cd build-subdir
      ../autogen.sh

      echo "#!/bin/sh
      exit 0
      " >> autogen.sh
      chmod +x autogen.sh
      ln -s ../configure configure
      cd ..
      # end of a workaround for LP: #1882255
      # Build
      snapcraftctl build

      rsync --remove-source-files -arhvP $SNAPCRAFT_PART_INSTALL/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/* $SNAPCRAFT_PART_INSTALL/usr/
      rm -rf $SNAPCRAFT_PART_INSTALL/snap/$SNAPCRAFT_PROJECT_NAME/current/usr

      # Copy the generated apparmor template into the install dir
      # it will be used by libvirt at runtime.
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/libvirt/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/abstractions
      cp $SNAPCRAFT_PART_BUILD/src/security/apparmor/TEMPLATE.qemu $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/libvirt/TEMPLATE.qemu
      cp $SNAPCRAFT_PART_BUILD/src/security/apparmor/libvirt-qemu $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/abstractions/libvirt-qemu
      # While LXC is not used, the AppArmor code errors out if the template for LXC is not there.
      cp $SNAPCRAFT_PART_BUILD/src/security/apparmor/TEMPLATE.lxc $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/libvirt/TEMPLATE.lxc
      cp $SNAPCRAFT_PART_BUILD/src/security/apparmor/libvirt-lxc $SNAPCRAFT_PART_INSTALL/etc/apparmor.d/abstractions/libvirt-lxc

  templates:
    source: templates/
    plugin: dump
    organize:
      '*': templates/  

  bin:
    source: bin/
    plugin: dump
    organize:
      '*': bin/

  networking:
    plugin: nil
    after:
      - uca-sources
    stage-packages:
      - openvswitch-switch
      - openvswitch-switch-dpdk
      - ovn-host
    organize:
       # Deal with alternatives usage in deb packages.
       usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk: usr/sbin/ovs-vswitchd

  openstack:
    plugin: nil
    after:
      - uca-sources
    stage-packages:
      - python3-nova
      - python3-neutron
      - python3-os-vif
      - python3-os-brick
      - python3-distutils
      - python3-systemd
      - haproxy
      - util-linux
    override-build: |
      snapcraftctl build
      # NOTE:
      # purge libvirt0 provided components to avoid
      # conflicts with the libvirt part provided versions
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/libvirt
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/*/libvirt*
      # purge some dangling symlinks
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt

  snap-hooks:
    plugin: python
    build-environment:
      # Workaround to ensure rebuild of snap work
      - PATH: /usr/bin:$PATH
      - PYTHONPATH: ''
    source: .
    after:
      - openstack

slots:
  hypervisor-config:
    interface: content
    source:
      write:
        - $SNAP_COMMON/run/hypervisor-config

hooks:
  install:
    plugs: [ network, microstack-support]
  configure:
    plugs: [ network, microstack-support]
  connect-slot-hypervisor-config:
    plugs:
      - network
      - network-bind
      - microstack-support
